### ISSUE TITLE
コンポーネントのテスト・型

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolf-client#47]
# 方針
Jest + Enzymeあたり
とりあえずPresentational Componentだけ．~残りどうするかわからない．~
~Container Componentは型だけ．~
名前は`*.test.js`にする．
`test/`は作らない．
同じディレクトリに突っ込む．

# やること
## 準備
- [x] Webpackのバンドルの対象から`*.test.js`を除外する． #48
- [x] Jestの導入 #48
- [x] Enzymeの導入 #48

### Presentational Components
- [x] AdvancedSearch.js #253 
- [x] AdvancedSearchBox.js #253
- [x] AdvancedSearchBoxRow.js #253
- [x] AdvancedSearchProp.js
- [x] App.js #159 
- [x] AsideContent.js #127
- [x] Avatar.js
- [x] AvatarItem.js #128 
- [x] AvatarList.js #129 
- [x] AvatarSelect.js #162 
- [x] BuildVillage.js #149 
- [x] ~EditableVillageItem.js~BuildVillageBox.js #148 
- [x] ConnectingToRobotPlayer.js #137 
- [x] EmailInput.js
- [x] Header.js #130
- [x] History.js #146 
- [x] IdSearch.js #253
- [x] IdSearchBox.js #253 
- [x] LanguageSelect.js
- [x] LobbyForAudience.js #143 
- [x] LobbyForHumanPlayer.js #144 
- [x] LobbyForRobotPlayer.js #145 
- [x] Main.js 98015df a93c3c3
- [x] MainContent.js #131
- [x] Member.js #142 
- [x] MemberRole.js #135 
- [x] MemberSelect.js
- [x] Menu.js #134 
- [x] MenuItem.js #132 
- [x] NumberSelect.js #138 
- [x] PasswordInput.js
- [x] Player.js #133 
- [x] SelectableMember.js #141 
- [x] Settings.js #136 
- [x] SettingsBox.js
- [x] TextareaInput.js
- [x] TextInput.js
- [x] VillageItem.js #139 
- [x] VillageList.js #140 
- [x] WaitingForPlayers.js #147 

### Container Components
- [x] AdvancedSearchContainer.js #253 
- [ ] App.js
- [x] BuildVillageContainer.js #158 #226 
- [x] ConnectingToRobotPlayerContainer.js #157 #218
- [x] HistoryContainer.js #156 #219 
- [x] IdSearchContainer.js #253 
- [ ] IntlProviderContainer.js
- [x] LobbyForAudienceContainer.js #155 #220
- [x] LobbyForHumanPlayerContainer.js #154 #221
- [x] LobbyForRobotPlayerContainer.js #153 #222 
- [x] MainContainer.js #152 #223
- [x] SettingContainer.js #151 #224 
- [x] WaitingForPlayersContainer.js #150 #225 

### Presentational Components
- [x] Activity.js #68 #91 
- [x] AgentIcon #51 #85 
- [x] Chat.js #67 #92 #190 
- [x] ChatDate.js #67 
- [x] ChatDelimeter.js #245
- [x] ChatIcon.js
- [x] ChatItem.js #67
- [x] ChatNum.js #67 
- [x] ChatText.js #67 
- [x] Command.js #90 
- [x] CommandInput.js #90
- [x] CommandInputBox.js #90
- [x] CommandNavigation.js #192 
- [x] CommandNavigationButton.js #192 
- [x] ~CommandOption.js~ #61 #74 
- [x] CommandPostMortem.js #192 
- [x] CommandSelection.js #90 #94 #116 
- [x] Day.js #53 #75 #95 
- [x] DayContainer.js #95 
- [x] Description.js #61 #76 
- [x] FormattedTime.js #49  #77
- [x] HideButton.js #60 #69 #96 
- [x] Info.js #54 #78 
- [x] Modal.js #61 #79 
- [x] Obfucator.js #59 
- [ ] Prediction.js #98 
- [x] PredictionItem.js #58 #98 
- [x] PredictionPlayer.js #56 #98 
- [x] PredictionRole.js #57 #98 
- [x] Result.js #83 #99 #191 
- [x] ResultCell.js #65 #83 #191
- [x] ResultClose.js #191 
- [x] Role.js #51 
- [x] ~RoleIcon.js~ -> AgentIcon #51 #85 
- [x] RoleText.js #51 
- [x] Timer.js #52  #66 #105 

### Container Components
- [x] ActivityContainer.js #91  #198 
- [ ] App.js
- [x] ChatContainer.js #92 #190 #199 #245 
- [x] CommandContainer.js #93 #200
- [x] CommandInputBoxContainer.js #201 
- [ ] CommandNavigationContainer.js
- [x] CommandPostMortemContainer.js #202 
- [x] CommandSelectionContainer.js #90 #94 #206 
- [x] DayContainer.js  #207 
- [x] HideButtonContainer.js #96 #208 
- [ ] ModalContainer.js
- [x] ObfucatorContainer.js #209 
- [x] PredictionContainer.js #98 #210 
- [x] ResultContainer.js #99 #191 #238 
- [x] RoleContainer.js #211 
- [x] ~TimerContainer.js~ #105

# ref
- https://redux.js.org/recipes/writing-tests#components
- https://redux.js.org/recipes/writing-tests#connected-components

**Comment by nimiusrd** [comment]
ここで管理する意味合いが薄くなったので閉じる
